---

- name: Download Grafana nightly build package archive.
  get_url:
    url: "https://grafanarel.s3.amazonaws.com/builds/grafana-{{ grafana_version }}.linux-x64.tar.gz"
    dest: /opt/
  when: grafana_build == 'nightly'

- name: Download Grafana release build package archive.
  get_url:
    url: "https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana-{{ grafana_version }}.linux-x64.tar.gz"
    dest: /opt/
  when: grafana_build == 'release'

- name: Unpack Grafana package archive.
  unarchive:
    src: "/opt/grafana-{{ grafana_version }}.linux-x64.tar.gz"
    dest: /opt/
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
