---

- name: Ensure Grafana group is present.
  group:
    name: "{{ grafana_group }}"
    state: present

- name: Ensure Grafana user is present.
  user:
    name: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    system: True
    state: present

- block:

    - name: Download checksum file for Grafana nightly build package archive.
      get_url:
        url: "https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana-{{ grafana_version }}.linux-x64.tar.gz.sha256"
        dest: /opt/

    - name: Set checksum variable.
      shell: "cat /opt/grafana-{{ grafana_version }}.linux-x64.tar.gz.sha256"
      register: checksum

    - name: Download Grafana nightly build package archive.
      get_url:
        url: "https://grafanarel.s3.amazonaws.com/builds/grafana-{{ grafana_version }}.linux-x64.tar.gz"
        dest: /opt/
        checksum: "sha256:{{ checksum.stdout }}"
      register: download_status

  when: grafana_build == 'nightly'

- block:

    - name: Download checksum file for Grafana release build package archive.
      get_url:
        url: "https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana-{{ grafana_version }}.linux-x64.tar.gz.sha256"
        dest: /opt/

    - name: Set checksum variable.
      shell: "cat /opt/grafana-{{ grafana_version }}.linux-x64.tar.gz.sha256"
      register: checksum

    - name: Download Grafana release build package archive.
      get_url:
        url: "https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana-{{ grafana_version }}.linux-x64.tar.gz"
        dest: /opt/
        checksum: "sha256:{{ checksum.stdout }}"
      register: download_status

  when: grafana_build == 'release'

- name: Unpack Grafana package archive.
  shell: "cd /opt && tar xfz grafana-{{ grafana_version }}.linux-x64.tar.gz"
  when: download_status.changed

- name: Get latest installed Grafana version.
  shell: ls -l /opt/ | grep grafana | sort | head -n 1 | rev | cut -d " " -f 1 | rev
  register: grafana_installed_version
  changed_when: False

- name: Set permissions for grafana_home.
  file:
    path: "/opt/grafana-{{ grafana_installed_version }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    recurse: True

# - name: Unpack Grafana package archive.
#   unarchive:
#     src: "/opt/grafana-{{ grafana_version }}.linux-x64.tar.gz"
#     dest: /opt/
#     owner: "{{ grafana_user }}"
#     group: "{{ grafana_group }}"
