---

- block:

    - name: Download checksum file for Grafana nightly build package archive.
      get_url:
        url: "https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana-{{ grafana_version }}.linux-x64.tar.gz.sha256"
        dest: /opt/

    - name: Set checksum variable.
      shell: "cat /opt/grafana-{{ grafana_version }}.linux-x64.tar.gz.sha256"
      register: checksum

    - name: Download Grafana nightly build package archive.
      get_url:
        url: "https://grafanarel.s3.amazonaws.com/builds/grafana-{{ grafana_version }}.linux-x64.tar.gz"
        dest: /opt/
        checksum: "sha256:{{ checksum.stdout }}"

  when: grafana_build == 'nightly'

- block:

    - name: Download checksum file for Grafana release build package archive.
      get_url:
        url: "https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana-{{ grafana_version }}.linux-x64.tar.gz.sha256"
        dest: /opt/

    - name: Set checksum variable.
      shell: "cat /opt/grafana-{{ grafana_version }}.linux-x64.tar.gz.sha256"
      register: checksum

    - name: Download Grafana release build package archive.
      get_url:
        url: "https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana-{{ grafana_version }}.linux-x64.tar.gz"
        dest: /opt/
        checksum: "sha256:{{ checksum.stdout }}"

  when: grafana_build == 'release'

- name: Unpack Grafana package archive.
  unarchive:
    src: "/opt/grafana-{{ grafana_version }}.linux-x64.tar.gz"
    dest: /opt/
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
