---

- name: Install Grafana plugins.
  command: "/opt/grafana-{{ grafana_installed_version.stdout }}/bin/grafana-cli plugins install {{ item }}"
  with_items: "{{ grafana_plugins }}"
  notify: restart grafana

